### ISSUE TITLE
Can't connect to minions

### ISSUE THREAD

**Issue by cryptolands** [rimusz/coreos-multi-node-k8s-gce#3]
Hey, 

I got the bootstrap working without errors. After i do "set_k8s_access.sh" i get this:

/registry
/coreos.com

UNIT                MACHINE             ACTIVE  SUB
kube-apiserver.service      95e2584b.../10.240.168.11   active  running
kube-controller-manager.service 95e2584b.../10.240.168.11   active  running
kube-register.service       95e2584b.../10.240.168.11   active  running
kube-scheduler.service      95e2584b.../10.240.168.11   active  running

Minion identifier   Labels

---

when i do "fleetctl list-machines" i can see the master, but no minion...

I'm also able to create a pod or controller, but they don't get assigned a minion...

Any idea?

**Comment by cryptolands** [comment]
the minions fail in 2 units:
docker.service:
Feb 18 17:01:36 k8s-node-01.c.eighth-orbit-722.internal systemd[1]: Starting Docker Application Container Engine...
Feb 18 17:01:36 k8s-node-01.c.eighth-orbit-722.internal systemd[1]: Failed to load environment files: No such file or directory
Feb 18 17:01:36 k8s-node-01.c.eighth-orbit-722.internal systemd[1]: docker.service failed to run 'start-pre' task: No such file or directory
Feb 18 17:01:36 k8s-node-01.c.eighth-orbit-722.internal systemd[1]: Failed to start Docker Application Container Engine.
Feb 18 17:01:36 k8s-node-01.c.eighth-orbit-722.internal systemd[1]: Unit docker.service entered failed state.
Feb 18 17:01:36 k8s-node-01.c.eighth-orbit-722.internal systemd[1]: docker.service failed.

and

flannel.service:

Feb 18 17:01:31 k8s-node-01.c.eighth-orbit-722.internal flanneld[696]: E0218 17:01:31.290515 00696 main.go:137] Failed to create SubnetManager: 501: All the given peers are not reachable (Tried to connect to each peer twice and fai
Feb 18 17:01:33 k8s-node-01.c.eighth-orbit-722.internal flanneld[696]: E0218 17:01:33.291068 00696 main.go:137] Failed to create SubnetManager: 501: All the given peers are not reachable (Tried to connect to each peer twice and fai
Feb 18 17:01:35 k8s-node-01.c.eighth-orbit-722.internal flanneld[696]: E0218 17:01:35.291612 00696 main.go:137] Failed to create SubnetManager: 501: All the given peers are not reachable (Tried to connect to each peer twice and fai
Feb 18 17:01:36 k8s-node-01.c.eighth-orbit-722.internal systemd[1]: flannel.service start operation timed out. Terminating.
Feb 18 17:01:36 k8s-node-01.c.eighth-orbit-722.internal systemd[1]: flannel.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 18 17:01:36 k8s-node-01.c.eighth-orbit-722.internal systemd[1]: Failed to start flannel is an etcd backed overlay network for containers.
Feb 18 17:01:36 k8s-node-01.c.eighth-orbit-722.internal systemd[1]: Unit flannel.service entered failed state.
Feb 18 17:01:36 k8s-node-01.c.eighth-orbit-722.internal systemd[1]: flannel.service failed.

any Idea?

**Comment by rimusz** [comment]
I'm working on the new version of the script, should have it done by next week.
Try to use beta channel for now as the latest alpha did bring some changes to CoreOS

**Comment by rimusz** [comment]
should not be a problem anymore
