### ISSUE TITLE
kubelet and proxy don't support --etcd-servers anymore

### ISSUE THREAD

**Issue by soupdiver** [rimusz/coreos-multi-node-k8s-gce#6]
In `kube-kubelet.service` and `kube-proxy.service` you specify `--etcd_servers` as an argument. This is no longer supported by these tools and so they fail during start. Removing them "solves" that problem but I'm not sure if it has to be replaced with something else

**Comment by rimusz** [comment]
I know, it is out dated, will take of if in a few days.
Also etcd2 support will be added too

**Comment by rimusz** [comment]
@soupdiver here we go, scripts and fleet units got refactored to support latest Kubernetes versions and OS X/Linux provisioning machines
