### ISSUE TITLE
Missing file units/kube-register.service

### ISSUE THREAD

**Issue by soupdiver** [rimusz/coreos-multi-node-k8s-gce#7]
In https://github.com/rimusz/coreos-multi-node-k8s-gce/blob/master/3-install_k8s_fleet_units.sh#L43 you write `fleetctl start ./units/kube-register.service` but in https://github.com/rimusz/coreos-multi-node-k8s-gce/tree/master/units is no such file.

I get `Error creating units: unable to find Unit(kube-register.service) in Registry or on filesystem` when starting the units.

**Comment by rimusz** [comment]
@soupdiver thanks for reporting, got it fixed
